[build]
command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4" }

[[redirects]]
from = "/meet-and-greet/"
to = "/rsvp/"
status = 301

[[redirects]]
from = "/join/"
to = "/rsvp/"
status = 301

[[redirects]]
from = "/scholarship/"
to = "/pages/scholarship/"
status = 301
